# Stage 1: Build
FROM node:20 AS build
WORKDIR /app

COPY FRONT-END/package*.json ./
RUN npm install
COPY FRONT-END/ .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*

# ✅ แก้ไขบรรทัดนี้: ชี้เข้าไปที่ /app/dist/public 
# เพื่อเอาไฟล์ข้างในออกมาวางที่รูทของ Nginx ตรงๆ
COPY --from=build /app/dist/public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]