# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
COPY FRONT-END/package*.json ./
RUN npm install
COPY FRONT-END/ .
RUN npm run build

# Stage 2: Run
FROM node:20-alpine
WORKDIR /app
# ก๊อปปี้ไฟล์ที่จำเป็นจาก build stage
COPY --from=build /app/package*.json ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "start"]